# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='afisha_event_ref',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
