# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_auto_20171021_0536'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afisha_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('vk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Client')),
            ],
        ),
    ]
