# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20171021_0751'),
        ('events', '0002_event_afisha_event_ref'),
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_first_client', to='people.Client')),
                ('client_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_second_client', to='people.Client')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.RenameField(
            model_name='eventuser',
            old_name='vk_user',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='eventuser',
            old_name='afisha_event',
            new_name='event',
        ),
    ]
