# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_remove_client_is_deleted'),
        ('events', '0002_event_afisha_event_ref'),
        ('matching', '0002_auto_20171021_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_active_client', to='people.Client')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('passive_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_passive_client', to='people.Client')),
            ],
        ),
    ]
