# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_remove_client_is_deleted'),
        ('events', '0002_event_afisha_event_ref'),
        ('matching', '0003_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventuser',
            unique_together=set([('event', 'client')]),
        ),
    ]
