# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_auto_20171021_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='mark',
            field=models.BooleanField(default=True),
        ),
    ]
