# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_remove_client_is_deleted'),
        ('events', '0003_auto_20171021_2026'),
        ('matching', '0005_like_mark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('event', 'active_client', 'passive_client')]),
        ),
    ]
