# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('money', models.IntegerField()),
                ('is_deleted', models.BinaryField(default=False)),
                ('description', models.CharField(max_length=255)),
                ('avatar_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='EventUser',
        ),
    ]
