# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20171021_0536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='vk_id',
            new_name='vk_id_ref',
        ),
    ]
